workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Build unsigned ipa
        script: |
          xcodebuild \
            -project AttendanceDebt.xcodeproj \
            -scheme AttendanceDebt \
            -sdk iphoneos \
            -configuration Release \
            build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/Release-iphoneos/*.app

