workflows:
  ios-sideload-build:
    name: iOS Sideload Build (7-Day Signature)
    instance_type: mac_mini_m2
    environment:
      vars:
        # Define your desired bundle ID here
        BUNDLE_ID: "com.Athkull.AttendanceDebt"
      xcode: latest
    scripts:
      - name: Set Bundle Identifier
        script: | 
          # This script updates your Info.plist with the correct bundle ID
          # It's cleaner than passing it as a build argument.
          PLIST_PATH=$(find . -name "Info.plist")
          plutil -replace CFBundleIdentifier -string $BUNDLE_ID $PLIST_PATH
          echo "Bundle ID set to $BUNDLE_ID"

      - name: Build and Sign IPA
        script: | 
          # This single command handles building, archiving, and signing the IPA.
          # It automatically uses the credentials you set up in the Codemagic UI.
          xcode-project build-ipa \
            --project "AttendanceDebt.xcodeproj" \
            --scheme "AttendanceDebt"
    artifacts:
      # This finds the generated IPA and makes it available for download
      - build/ios/ipa/*.ipa
    publishing:
      # This enables the automatic code signing feature
      app_store_connect:
        apple_id: kulatharv20@gmail.com              # These are read from the UI
        app_specific_password: milb-wcgc-srwo-zhlh   # These are read from the UI
