workflows:
  ios-simple:
    name: iOS Simple Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.example.AttendanceDebt
      vars:
        XCODE_PROJECT: "AttendanceDebt.xcodeproj"
        XCODE_SCHEME: "AttendanceDebt"
      xcode: latest
    scripts:
      - name: Build ipa
        script: |
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
